# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lisp: [sbcl, ecl]
        exclude:
          - os: windows-latest
            lisp: [ecl]
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install SBCL (Linux)
        if: runner.os == 'Linux' && matrix.lisp == 'sbcl'
        run: sudo apt-get install -y sbcl

      - name: Install ECL (Linux)
        if: runner.os == 'Linux' && matrix.lisp == 'ecl'
        run: sudo apt-get install -y ecl

      - name: Install SBCL (macOS)
        if: runner.os == 'macOS' && matrix.lisp == 'sbcl'
        run: brew install sbcl

      - name: Install ECL (macOS)
        if: runner.os == 'macOS' && matrix.lisp == 'ecl'
        run: brew install ecl

      - name: Install SBCL (Windows)
        if: runner.os == 'Windows'
        run: choco install sbcl

      - name: Install Quicklisp and ql-https
        env:
          LISP: ${{matrix.lisp}}
        run: ./install.sh

      - name: Run tests
        env:
          CI: 1
          LISP: ${{matrix.lisp}}
        run: |
          $LISP <<EOF
          (require 'asdf)
          (push (uiop:getcwd) asdf:*central-registry*)
          (ql:quickload "ql-https/test")
          (asdf:test-system "ql-https")
          (uiop:quit)
          EOF

